// Display
export const EXPAND_DOCK = 'EXPAND_DOCK';
export const TOGGLE_DOCK = 'TOGGLE_DOCK';

// Cards
export const OPEN_CARD = 'OPEN_CARD';
export const SET_ACTIVE_CARD_INDEX = 'SET_ACTIVE_CARD_INDEX';
export const CLOSE_CARD = 'CLOSE_CARD';
export const CLOSE_ALL_CARDS = 'CLOSE_ALL_CARDS';
export const ADJUST_CARDS_DIMENSIONS = 'ADJUST_CARDS_DIMENSIONS';
export const CHANGE_ANSWER_EDITOR = 'CHANGE_ANSWER_EDITOR';
export const CHANGE_DESCRIPTION_EDITOR = 'CHANGE_DESCRIPTION_EDITOR';
export const EDIT_CARD = 'EDIT_CARD';
export const ENABLE_EDITOR = 'ENABLE_EDITOR';
export const DISABLE_EDITOR = 'DISABLE_EDITOR';
export const ADJUST_DESCRIPTION_SECTION_HEIGHT = 'ADJUST_DESCRIPTION_SECTION_HEIGHT';
export const OPEN_MODAL = 'OPEN_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';
export const SAVE_CARD = 'SAVE_CARD';
export const OPEN_CARD_SIDE_DOCK = 'OPEN_CARD_SIDE_DOCK';
export const CLOSE_CARD_SIDE_DOCK = 'CLOSE_CARD_SIDE_DOCK';
export const OPEN_CARD_CREATE_MODAL = 'OPEN_CARD_CREATE_MODAL';
export const CLOSE_CARD_CREATE_MODAL = 'CLOSE_CARD_CREATE_MODAL';

// Ask
export const UPDATE_ASK_SEARCH_TEXT = 'UPDATE_ASK_SEARCH_TEXT';
export const CHANGE_ASK_INTEGRATION = 'CHANGE_ASK_INTEGRATION';
export const UPDATE_ASK_QUESTION_TITLE = 'UPDATE_ASK_QUESTION_TITLE';
export const UPDATE_ASK_QUESTION_DESCRIPTION = 'UPDATE_ASK_QUESTION_DESCRIPTION';
export const ADD_ASK_RECIPIENT = 'ADD_ASK_RECIPIENT';
export const REMOVE_ASK_RECIPIENT = 'REMOVE_ASK_RECIPIENT';
export const UPDATE_ASK_RECIPIENT = 'UPDATE_ASK_RECIPIENT';
export const ADD_ASK_SCREEN_RECORDING_CHUNK = 'ADD_ASK_SCREEN_RECORDING_CHUNK';
export const START_ASK_SCREEN_RECORDING = 'START_ASK_SCREEN_RECORDING';
export const END_ASK_SCREEN_RECORDING = 'END_ASK_SCREEN_RECORDING';
export const ASK_SCREEN_RECORDING_ERROR = 'ASK_SCREEN_RECORDING_ERROR'