export const EXPAND_DOCK = 'EXPAND_DOCK';
export const TOGGLE_DOCK = 'TOGGLE_DOCK';

export const OPEN_CARD = 'OPEN_CARD';
export const SET_ACTIVE_CARD_INDEX = 'SET_ACTIVE_CARD_INDEX';
export const CLOSE_CARD = 'CLOSE_CARD';
export const CLOSE_ALL_CARDS = 'CLOSE_ALL_CARDS';
export const EDIT_CARD = 'EDIT_CARD';
export const SAVE_CARD = 'SAVE_CARD';
export const OPEN_CARD_SIDE_DOCK = 'OPEN_CARD_SIDE_DOCK';
export const CLOSE_CARD_SIDE_DOCK = 'CLOSE_CARD_SIDE_DOCK';
export const OPEN_CARD_CREATE_MODAL = 'OPEN_CARD_CREATE_MODAL';
export const CLOSE_CARD_CREATE_MODAL = 'CLOSE_CARD_CREATE_MODAL';
