export const SETTING_SECTION_TYPE = {
  KNOWLEDGE_BASE: 'KNOWLEDGE_BASE',
  COMMUNICATION: 'COMMUNICATION',
  AUTOFIND: 'AUTOFIND',
  NOTIFICATIONS: 'NOTIFICATIONS'
};

export const USER_ROLE = {
  ADMIN: 'Admin',
  MEMBER: 'Member'
};

export const USER_BADGE = {
  BRONZE: 'Bronze',
  SILVER: 'Silver',
  GOLD: 'Gold',
  PLATINUM: 'Platinum',
};

export const ONBOARDING_COMPLETE = -1;

export default { SETTING_SECTION_TYPE, USER_ROLE, USER_BADGE, ONBOARDING_COMPLETE };