export const SETTING_SECTION_TYPE = {
  INTEGRATIONS: 'INTEGRATIONS',
  AUTOFIND: 'AUTOFIND',
  NOTIFICATIONS: 'NOTIFICATIONS',
  EXTERNAL_VERIFICATION: 'EXTERNAL_VERIFICATION',
  SEARCH_BAR: 'SEARCH_BAR'
};

export default { SETTING_SECTION_TYPE };
