import _ from 'lodash';
import { INTEGRATIONS as ALL_INTEGRATIONS } from './general';
import AUDIT from './audit';

export const SOURCE = _.pickBy(AUDIT.SOURCE, (value) =>
  [AUDIT.SOURCE.DOCK, AUDIT.SOURCE.AUTOFIND, AUDIT.SOURCE.SEGMENT].includes(value)
);

export const INTEGRATIONS = [
  ALL_INTEGRATIONS.CONFLUENCE,
  ALL_INTEGRATIONS.ZENDESK,
  ALL_INTEGRATIONS.SALESFORCE,
  ALL_INTEGRATIONS.GOOGLE,
  ALL_INTEGRATIONS.DROPBOX,
  ALL_INTEGRATIONS.SLACK,
  ALL_INTEGRATIONS.JIRA,
  ALL_INTEGRATIONS.GMAIL,
  ALL_INTEGRATIONS.OUTLOOK
];

export const PAGE_SIZE = 20;

export default { SOURCE, PAGE_SIZE, INTEGRATIONS };
